### ISSUE TITLE
Verification Siamese embedding

### ISSUE THREAD

**Issue by lodemo** [a-nagrani/VGGVox#2]
Hello,
thanks for sharing the trained model!

I wanted to use the verification model for extracting a speaker embedding, as described in the paper. There its explained that the embedding is trained as the output of a Siamese network at layer fc8 with a dimension of 256.
It seems that in the provided verification model the last layer has a dimension of 1024 instead of 256 (or the number of classes 1251).

Is this the correct embedding? or am i extracting the wrong layer 

I want to compare the embeddings with a distance function like proposed.

Regards

**Comment by a-nagrani** [comment]
Hi, 
Sorry for the late response - you are extracting the correct layer, the embedding has a dimension of 1024. The paper has been updated with minor fixes here: https://arxiv.org/pdf/1706.08612.pdf.
